# Generated by Django 5.2 on 2025-04-26 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='description',
            new_name='designation',
        ),
    ]
